version: '3.9'

services:
  frontend:
    image: nguyenchin0077/check-stk-lua-dao-frontend:latest # Kéo image từ Docker Hub
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: nguyenchin0077/check-stk-lua-dao-backend:latest # Kéo image từ Docker Hub
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/chongluadaoreact

  postgres:
    image: nguyenchin0077/postgres:lastes
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: chongluadaoreact
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
